In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a[0]

1

In [6]:
a[2]

3

In [ ]:
#numoy array vs Python list

In [6]:
import time
import sys


b=range(1000)
print(sys.getsizeof(5)* len(b))

28000


In [7]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [1]:
size=100000

In [4]:
L1= range(size)
L2= range(size)
A1=np.arange(size)
A2=np.arange(size)

In [14]:
start= time.time()
result = [(x+y) for x,y in zip (L1,L2)]
result = [(x+y) for x,y in zip (L1,L2)]
print("python list took :",(time.time()-start)*1000)

python list took : 30.971765518188477


In [13]:
start= time.time()
result=A1+A2
print("numpy array took :",(time.time()-start)*1000)

numpy array took : 0.6880760192871094


In [17]:
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a.ndim

2

In [19]:
a.itemsize

4

In [20]:
a.shape

(3, 2)

In [35]:
a= np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [36]:
a.itemsize

8

In [34]:
a= np.array([[1,2],[3,4],[5,6]],dtype=np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [50]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
l=range(5)
l

range(0, 5)

In [59]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [62]:
print('concatenation example:')
print(np.char.add (['hello','hi'],['abc','xyz']))

concatenation example:
['helloabc' 'hixyz']


In [69]:
print(np.char.multiply('Hello ',5))

Hello Hello Hello Hello Hello 


In [73]:
print(np.char.center('Hello ',20,fillchar='-'))

-------Hello -------


In [74]:
print(np.char.capitalize('hello world'))

Hello world


In [75]:
print(np.char.title('how are you doing ?'))

How Are You Doing ?


In [77]:
print(np.char.lower(['Hello world']))
print(np.char.lower('HELLO'))

['hello world']
hello


In [78]:
print(np.char.upper(['Hello world']))
print(np.char.upper('hello'))

['HELLO WORLD']
HELLO


In [79]:
print(np.char.split(' are you coming to the party ?'))

['are', 'you', 'coming', 'to', 'the', 'party', '?']


In [80]:
print(np.char.splitlines('hello\n how are you ?'))

['hello', ' how are you ?']


In [84]:
print(np.char.strip(['nina','admin','anita'],'a'))

['nin' 'dmin' 'nit']


In [85]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [86]:
print(np.char.replace('He was a good dancer','was','is'))

He is a good dancer
